CHANCE_TO_CHECK_OUTPUT_WHEN_IMAGES_FROM_MINERS_WERE_SIMILAR = 0.1

STATUS_OK = 200
STATUS_INTERNAL_SERVER_ERROR = 500

FAILED_RESPONSE_SCORE = 0.25

SYNTHETIC_ENDPOINT_PREFIX = "synthetic"
CHECKING_ENDPOINT_PREFIX = "checking"

AI_SERVER_PORT = 6919
